apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
