Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202508.03.0"
  config.vm.hostname = "knaktoS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.network "forwarded_port", host:8080, guest:80
  config.vm.provider "libvirt" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vm.synced_folder "./", "/tmp/p3"
  config.vm.provision "shell", name: "install-dependencies", run: "once", path: "script/install-dependencies.sh"

  config.vm.provision "shell", name: "setup-cluster", run: "once", path: "script/setup-cluster.sh"
end
