Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202508.03.0"
  config.vm.hostname = "knaktoS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.network "forwarded_port", host:8080, guest:80
  config.vm.provider "libvirt" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vm.synced_folder "./", "/tmp/p3"
  config.vm.provision "shell", name: "install dependencies", run: "once", inline: <<-SHELL
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/

    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh ./get-docker.sh
    sudo adduser vagrant docker

    curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
  SHELL

  config.vm.provision "shell", name: "install-argocd", run: "once", inline: <<-SHELL
    curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 /tmp/get_helm.sh
    /tmp/get_helm.sh

    curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v3.5.3/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd

    k3d cluster create -p "80:80@loadbalancer"
    k3d image import /tmp/p3/web/app.tar

    kubectl create namespace argocd
    kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    kubectl wait --for=condition=available deployment/argocd-server -n argocd --timeout=300s
    kubectl wait --for=condition=established --timeout=60s crd/applications.argoproj.io
    kubectl apply -f https://raw.githubusercontent.com/knakto/Inception-of-thing/main/src/p3/kubeconfig/argoconfig/config.yml
    # You have to command "argocd app sync kustomize-app --core" by your self after application already setup
    
    # mkdir -p /home/vagrant/.kube
    # k3d kubeconfig get k3s-default > /home/vagrant/.kube/config
    # use "mkdir .kube && k3d kubeconfig get k3s-default > .kube/config" to make kubectl work
    # use "kubectl config set-context --current --namespace=argocd" to change context befor run argocd command
  SHELL
end
