Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202508.03.0"
  config.vm.hostname = "knaktoS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.network "forwarded_port", host:8080, guest:80
  config.vm.provider "libvirt" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vm.synced_folder "./", "/tmp/p2"
  config.vm.provision "shell", name: "setup-server", run: "once", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -s -
      sudo k3s ctr i import /tmp/p2/apps.tar
      sudo kubectl apply -k /tmp/p2/kubeconfig
  SHELL
end
