Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"

  config.vm.synced_folder "secrets", "/var/secrets"
  config.vm.provision "shell", name: "secret-file-exists-check", run: "once", inline: <<-SHELL
    SECRET_FILES=(
      "/var/secrets/kube_token.txt"
      # add path to your secrets here (if you have more)
    )
    for FILE in "${SECRET_FILES[@]}"; do
      if [ ! -f "$FILE" ]; then
        exit 1
      fi
      if [ ! -s "$FILE" ]; then
        exit 1
      fi
    done
  SHELL

  server_ip = "192.168.56.110"
  agent_ip = "192.168.56.111"

  config.vm.define "knaktoS" do |ctl|
    ctl.vm.hostname = "knaktoS"
    ctl.vm.network "private_network", ip: server_ip
    ctl.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    ctl.vm.provision "shell", run: "once", name: "setup-k3s-server", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--token $(cat /var/secrets/kube_token.txt)" sh -s -
      rm -rf /var/secrets/kube_token.txt
    SHELL
  end

  config.vm.define "knaktoSW" do |ctl|
    ctl.vm.hostname = "knaktoSW"
    ctl.vm.network "private_network", ip: agent_ip
    ctl.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    ctl.vm.provision "shell", run: "once", name: "setup-k3s-agent", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --server https://#{server_ip}:6443 --token $(cat /var/secrets/kube_token.txt)" sh -s -
      rm -rf /var/secrets/kube_token.txt
    SHELL
  end
end
