apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: app-release
  source:
    path: src/p3/kubeconfig/my-app
    repoURL: 'https://github.com/knakto/Inception-of-thing.git'
    targetRevision: HEAD
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
