apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app
  namespace: argocd
spec:
  project: default
  source:
    path: src/p3/kubeconfig/appconfig
    repoURL: 'https://github.com/knakto/Inception-of-thing.git'
    targetRevision: HEAD
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
