apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - web1-deploy.yml
  - web1-ingress.yml
  - web1-service.yml
  - web2-deploy.yml
  - web2-ingress.yml
  - web2-service.yml
  - web3-deploy.yml
  - web3-ingress.yml
  - web3-service.yml
